config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'users#logout', as: :logout_user

  resources :users

  resources :sales do
    collection do
      get "upload_form", to: "sales#upload_form"
      post "calculate_balance", to: "sales#calculate_balance"
      get "show_result", to: "sales#show_result"
      get "list_sales", to: "sales#list_sales"
    end
  end

  get 'up', to: 'rails/health#show', as: :rails_health_check
  
  root to: 'sales#list_sales'
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  
  validates :purchaser_name, presence: { message: "Campo obrigatório" }
  validates :item_description, presence: { message: "Campo obrigatório" }
  validates :item_price, presence: { message: "Campo obrigatório" }
  validates :purchase_count, presence: { message: "Campo obrigatório" }
  validates :merchant_address, presence: { message: "Campo obrigatório" }
  validates :merchant_name, presence: { message: "Campo obrigatório" }

  def self.calculate_total_balance(parsed_data)
    total_balance = parsed_data.sum { |data| data['item_price'].to_f * data['purchase_count'].to_i }
    total_balance
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :require_login

  def upload_form
    @sale = Sale.new
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = current_user.sales.build(sale_params)
    
    if @sale.save
      flash[:success] = 'Venda adicionada com sucesso.'
      redirect_to list_sales_sales_path
    else
      flash.now[:alert] = 'Erro ao adicionar venda.'
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @sale = current_user.sales.find(params[:id])
  end

  def update
    @sale = current_user.sales.find(params[:id])

    if @sale.update(sale_params)
      flash[:success] = 'Venda atualizada com sucesso.'
      redirect_to list_sales_sales_path
    else
      flash.now[:alert] = 'Erro ao atualizar venda.'
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @sale = current_user.sales.find(params[:id])
    @sale.destroy
    flash[:success] = 'Venda excluída com sucesso.'
    redirect_to list_sales_sales_path
  end

  def list_sales
    if current_user
      @sales = current_user.sales.paginate(page: params[:page], per_page: 10)
  
      if params[:search_term].present?
        search_term = "%#{params[:search_term]}%"
        @sales = @sales.where(
          "CAST(purchaser_name AS TEXT) LIKE ? OR CAST(item_description AS TEXT) LIKE ? OR CAST(item_price AS TEXT) LIKE ? OR CAST(purchase_count AS TEXT) LIKE ? OR CAST(merchant_address AS TEXT) LIKE ? OR CAST(merchant_name AS TEXT) LIKE ?", 
          search_term, search_term, search_term, search_term, search_term, search_term
        )
      end
    else
      flash[:alert] = 'Você precisa estar logado para acessar esta página.'
      redirect_to login_path
      return
    end
  
    @sales ||= []
  
    respond_to do |format|
      format.html do
        if @sales.empty?
          flash.now[:notice] = "Nenhum resultado encontrado para a pesquisa."
        end
      end
      format.json { render json: @sales }
    end
  end
  

  def show_result
    @total_balance = flash[:total_balance]
  end

  def calculate_balance
    begin
      if params[:sale] && params[:sale][:file].present?
        file_content = params[:sale][:file].read
        parsed_data = parse_file_content(file_content)

        if parsed_data.present?
          current_user.sales.destroy_all

          parsed_data.each do |data|
            @sale = current_user.sales.build(data)

            unless @sale.save
              flash[:alert] = "Falha no processamento do arquivo."
              redirect_to upload_form_sales_path
              return
            end
          end

          total_balance = Sale.calculate_total_balance(parsed_data)
          flash[:total_balance] = total_balance
          redirect_to show_result_sales_path
        else
          flash[:alert] = "Falha no processamento do arquivo."
          redirect_to upload_form_sales_path
        end
      else
        flash[:alert] = "Arquivo não encontrado."
        redirect_to upload_form_sales_path
      end
    rescue StandardError => e
      flash[:alert] = "Erro durante o processamento do arquivo: #{e.message}"
      redirect_to list_sales_sales_path
    end
  end

  private

  def sale_params
    params.require(:sale).permit(
      :purchaser_name, 
      :item_description, 
      :item_price, 
      :purchase_count, 
      :merchant_address, 
      :merchant_name
    )
  end

  def parse_file_content(content)
    lines = content.force_encoding("UTF-8").split("\n")
    header = lines.shift.split("\t").map { |column| column.downcase.gsub(" ", "_").strip }

    parsed_data = []
    lines.each do |line|
      values = line.force_encoding("UTF-8").split("\t").map(&:strip)
      data_hash = Hash[header.zip(values)]
      parsed_data << data_hash
    end

    Rails.logger.info("parsed data: #{parsed_data}")

    parsed_data
  end

  private

  def require_login
    unless current_user
      flash[:alert] = 'Você precisa estar logado para acessar esta página.'
      redirect_to login_path
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with model: sale do |form| %>
  <div class="sale-field">
    <%= form.label :purchaser_name, "Nome do Comprador", class: 'sale-label' %>
    <%= form.text_field :purchaser_name, class: 'sale-input', maxlength: "30", minlength: "10" %>
    <% if @sale.errors[:purchaser_name].any? %>
      <% @sale.errors[:purchaser_name].each do |message| %>
      <p class="error"><%= message %></p>
    <% end %>
    <% end %>
  </div>

  <div class="sale-field">
    <%= form.label :item_description, "Descrição do Item", class: 'sale-label' %>
    <%= form.text_field :item_description, class: 'sale-input', maxlength: "30", minlength: "10" %>
    <% if @sale.errors[:item_description].any? %>
      <% @sale.errors[:item_description].each do |message| %>
      <p class="error"><%= message %></p>
    <% end %>
    <% end %>
  </div>

  <div class="sale-field">
    <%= form.label :item_price, "Valor do Item", class: 'sale-label edit-sale-numeric' %>
    <%= form.number_field :item_price, class: 'sale-input', maxlength: "4", minlength: "2" %>
    <% if @sale.errors[:item_price].any? %>
      <% @sale.errors[:item_price].each do |message| %>
      <p class="error"><%= message %></p>
    <% end %>
    <% end %>
  </div>

  <div class="sale-field">
    <%= form.label :purchase_count, "Quantidade", class: 'sale-label edit-sale-numeric' %>
    <%= form.text_field :purchase_count, class: 'sale-input', maxlength: "2", minlength: "1" %>
    <% if @sale.errors[:purchase_count].any? %>
      <% @sale.errors[:purchase_count].each do |message| %>
      <p class="error"><%= message %></p>
    <% end %>
    <% end %>
  </div>

  <div class="sale-field">
    <%= form.label :merchant_address, "Endereço do vendedor", class: 'sale-label' %>
    <%= form.text_field :merchant_address, class: 'sale-input', maxlength: "30", minlength: "10" %>
    <% if @sale.errors[:merchant_address].any? %>
      <% @sale.errors[:merchant_address].each do |message| %>
      <p class="error"><%= message %></p>
    <% end %>
    <% end %>
  </div>

  <div class="sale-field">
    <%= form.label :merchant_name, "Nome do Vendedor", class: 'sale-label' %>
    <%= form.text_field :merchant_name, class: 'sale-input', maxlength: "30", minlength: "10" %>
    <% if @sale.errors[:merchant_name].any? %>
      <% @sale.errors[:merchant_name].each do |message| %>
      <p class="error"><%= message %></p>
    <% end %>
    <% end %>
  </div>

  <div class="sale-field">
    <%= form.submit 'Adicionar Venda', class: 'sale-submit' %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<div class="sale-container">
  <h1 class="sale-heading">Editar Venda</h1>
  <%= render 'form', sale: @sale %>
</div>

app/views/sales/index.html.erb
<p>Saldo Total: <%= @total_balance %></p>

app/views/sales/list_sales.html.erb
<!-- app/views/sales/list_sales.html.erb -->

<!DOCTYPE html>
<html lang="pt-Br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lista de Vendas</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "material_styles", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <div class="content-container">

    <%= link_to 'Adicionar Venda', new_sale_path, class: 'btn btn-add-sale btn-add-sale-top' %>

    <h1 class="custom-heading">Lista de Vendas</h1>

    <%= form_tag list_sales_sales_path, method: :get, class: 'search-form' do %>
      <%= text_field_tag :search_term, params[:search_term], placeholder: 'Digite para pesquisar', class: 'search-input' %>
      <%= submit_tag 'Pesquisar', class: 'btn btn-primary' %>
    <% end %>

    <% if @sales.present? %>
      <table class="custom-table">
        <thead>
          <tr>
            <th>Nome do Comprador</th>
            <th>Descrição do Item</th>
            <th>Preço do Item</th>
            <th>Quantidade</th>
            <th>Endereço do Vendedor</th>
            <th>Nome do Vendedor</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <% @sales.each do |sale| %>
            <tr>
              <td><%= sale.purchaser_name %></td>
              <td><%= sale.item_description %></td>
              <td><%= sale.item_price %></td>
              <td><%= sale.purchase_count %></td>
              <td><%= sale.merchant_address %></td>
              <td><%= sale.merchant_name %></td>
              <td>
                <div class="action-buttons">
                  <%= link_to 'Editar', edit_sale_path(sale), class: 'btn btn-primary', title: 'Editar' %>
                  <%= link_to 'Excluir', sale, data: { turbo_method: :delete, turbo_confirm: 'Você tem certeza?' }, class: 'btn btn-danger', title: 'Excluir' %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="custom-pagination">
        <%=
          will_paginate @sales,
          previous_label: '🡰 Anterior',
          next_label: 'Próximo 🡲'
         %>
      </div>
    <% else %>
      <p class="no-results-message">Nenhum resultado encontrado para a pesquisa.</p>
    <% end %>
  </div>
</body>
</html>

app/views/sales/new.html.erb
<div class="sale-container">
  <h1 class="sale-heading">Nova Venda</h1>
  <%= render 'form', sale: @sale %>
</div>

app/views/sales/show_result.html.erb
<div style="text-align: center; margin-top: 50px;">
  <h2>Saldo Total</h2>

  <% if @total_balance.present? %>
    <p style="font-size: 24px; color: green;"><%= number_to_currency(@total_balance, unit: "R$", precision: 2) %></p>
  <% else %>
    <p style="font-size: 24px; color: red;">Erro durante o processamento do arquivo. <a href="/">Tentar novamente</a></p>
  <% end %>
</div>

app/views/sales/upload_form.html.erb
<div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
  <div style="width: 400px; padding: 20px; border: 1px solid #ccc; border-radius: 8px;">
    <%= form_with(model: @sale, url: calculate_balance_sales_path, multipart: true) do |form| %>
      <div style="margin-bottom: 10px;">
        <%= form.file_field :file %>
      </div>
      <div style="margin-bottom: 10px;">
        <%= form.submit "Enviar", class: "btn btn-primary" %>
      </div>

      <% if flash.now[:alert] %>
        <div style="color: red; margin-bottom: 10px;">
          <%= flash.now[:alert] %>
        </div>
      <% end %>

      <% if flash.now[:notice] %>
        <div style="color: green; margin-bottom: 10px;">
          <%= flash.now[:notice] %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>