config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'users#logout', as: :logout_user

  resources :users

  resources :sales do
    collection do
      get "upload_form", to: "sales#upload_form"
      post "calculate_balance", to: "sales#calculate_balance"
      get "show_result", to: "sales#show_result"
      get "list_sales", to: "sales#list_sales"
    end
  end

  get 'up', to: 'rails/health#show', as: :rails_health_check
  
  root to: 'sales#list_sales'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sistema de Vendas</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", "users", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <nav class="main-navigation">
    <ul>
    <% if session[:user_id] %>
      <li><%= link_to 'Upload de Arquivo', upload_form_sales_path %></li>
      <li><%= link_to 'Listagem de Vendas', list_sales_sales_path %></li>
      <% if current_user && current_user.admin? %>
        <li><%= link_to 'Listagem de Usuários', users_path %></li>
      <% end %>
    <% end %>
      <% if session[:user_id] %>
        <li class="welcome-message">Bem-vindo, <%= session[:user_name] %>!</li>
        <li><%= button_to 'Sair', logout_path, method: :delete, class: 'logout-button' %></li>
      <% else %>
        <li><%= link_to 'Entrar', login_path %></li>
        <li><%= link_to 'Registre-se', new_user_path, class: "form-link" %></li>
      <% end %>
    </ul>
  </nav>
  <%= yield %>
</body>
</html>